<?php
require_once('Automate.php');

$help="
automate-composer-del

This command is responsible for deleting the test files generated by the project.

Usage:

-r --repositories-path      folder path where the generated test repositories
-d --directories-file-path  paths of the generated repositories in a file.
";

$argumentos = getopt("r:d:", array(
    "repositories-path:",
    "directories-file-path:"
));

//If the options are not set, we exit and indicate the usage mode.
if (
    !(isset($argumentos["r"]) || isset($argumentos["repositories-path"]))
    ||
    !(isset($argumentos["d"]) || isset($argumentos["directories-file-path"]))
) {
    exit($help);
}

//All options are well established until here
$repositoriesPath = isset($argumentos["r"]) ? $argumentos["r"] : $argumentos["repositories-path"];
if (substr($repositoriesPath, -1)!="/"){
	$repositoriesPath  = $repositoriesPath . "/";
}

$directoriesFilePath = isset($argumentos["d"]) ? $argumentos["d"] : $argumentos["directories-file-path"];
echo "automate-composer-del" . PHP_EOL;
echo "delete repository files for testing." . PHP_EOL;
echo "repositories-path: $repositoriesPath" . PHP_EOL;
echo "directories-file-path: $directoriesFilePath" . PHP_EOL;

composer_del($repositoriesPath, $directoriesFilePath);
echo "files deleted successfully." . PHP_EOL;
